twitter-status-data:
  string-list:
    - abc
    - def
    - aaf
    - fsa
    - ef
  min-length: 10
  max-length: 25

retry-config:
  initial-interval-ms:
  max-interval-ms:
  multiplier:
  max-attempts:
  sleep-time-ms:

kafka-config-data:
  kafka-broker-list:
  schema-registry-key-url:
  schema-registry:
  topic-name:
  topic-names-to-create:
  num-of-partitions:
  replication-factor:

kafka-producer-config:
  key-serializer-class: org.apache.kafka.common.serialization.LongSerializer
  value-serializer-class: io.confluent.kafka.serializers.KafkaAvroSerializer
  compression-type: snappy
  acks: all
  batch-size: 16384
  batch-size-boost-factor: 100
  linger-ms: 5
  request-timeout-ms: 60000
  retry-count: 5
