spring:
  cloud:
    loadBalancer:
      ribbon:
        enabled: false
  profiles:
    active: singleserver

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    appname: service-registry-cluster



#---
#server:
#  port: 8761
#spring:
#  profiles: peer1
#eureka:
#  instance:
#    hostname: discovery-service-1
#    metadataMap:
#      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#  client:
#    serviceUrl:
#      defaultZone: http://discovery-service-1:8761/eureka/,http://discovery-service-2:8762/eureka/
#log:
#  app-name: discovery-service-1
#
#---
#service:
#  port: 8762
#spring:
#  profiles: peer2
#eureka:
#  instance:
#    hostname: discovery-service-2
#    metadataMap:
#      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#  client:
#    serviceUrl:
#      defaultZone: http://discovery-service-2:8762/eureka/,http://discovery-service-1:8761/eureka/
#log:
#  app-name: discovery-service-2
